/**
 * ItemSheetDocument — React-PDF document component for item sheet export.
 *
 * Defines the PDF layout:
 *   - Header: "ManteMap — Item Sheet", project name, export date
 *   - Item name + status + type
 *   - Dynamic fields table (field name → value, null → "—")
 *   - Documents list (name + expiry date)
 *   - QR code embedded (optional, gracefully omitted if unavailable per PDF-003)
 *   - Footer: page numbers, "Generated by ManteMap"
 *
 * Spec: openspec/changes/phase-11-advanced-features/specs/pdf-export/spec.md
 *   PDF-001, PDF-002, PDF-003
 * Design: openspec/changes/phase-11-advanced-features/design.md
 */

import React from 'react';
import {
  Document,
  Page,
  Text,
  View,
  StyleSheet,
  Image,
} from '@react-pdf/renderer';

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export interface ItemSheetDocumentProps {
  itemName: string;
  itemSlug: string;
  status: string | null;
  itemType: string | null;
  fields: Array<{ name: string; value: unknown }>;
  documents: Array<{ name: string; expiresAt: string | null }>;
  projectName: string;
  qrDataUrl?: string;
  locationPath?: string;
  exportDate: string;
}

// ---------------------------------------------------------------------------
// Styles
// ---------------------------------------------------------------------------

const styles = StyleSheet.create({
  page: {
    padding: 40,
    fontSize: 11,
    fontFamily: 'Helvetica',
    color: '#1f2937',
  },
  header: {
    marginBottom: 20,
    borderBottom: '2 solid #2563eb',
    paddingBottom: 10,
  },
  headerTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#2563eb',
  },
  headerSubtitle: {
    fontSize: 10,
    color: '#6b7280',
    marginTop: 4,
  },
  headerDate: {
    fontSize: 9,
    color: '#9ca3af',
    marginTop: 2,
  },
  section: {
    marginBottom: 16,
  },
  sectionTitle: {
    fontSize: 13,
    fontWeight: 'bold',
    color: '#374151',
    borderBottom: '1 solid #e5e7eb',
    paddingBottom: 4,
    marginBottom: 8,
  },
  itemInfo: {
    flexDirection: 'row',
    gap: 16,
    marginBottom: 16,
  },
  itemName: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#111827',
    flex: 1,
  },
  itemMeta: {
    fontSize: 10,
    color: '#6b7280',
  },
  badge: {
    backgroundColor: '#dbeafe',
    color: '#1e40af',
    fontSize: 9,
    fontWeight: 'bold',
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 4,
  },
  table: {
    width: '100%',
  },
  tableRow: {
    flexDirection: 'row',
    borderBottom: '1 solid #f3f4f6',
    paddingVertical: 5,
  },
  tableHeader: {
    flexDirection: 'row',
    borderBottom: '2 solid #e5e7eb',
    paddingVertical: 5,
    backgroundColor: '#f9fafb',
  },
  fieldLabel: {
    flex: 1,
    fontSize: 10,
    fontWeight: 'bold',
    color: '#374151',
  },
  fieldValue: {
    flex: 1,
    fontSize: 10,
    color: '#4b5563',
    textAlign: 'right',
  },
  fieldLabelHeader: {
    flex: 1,
    fontSize: 9,
    fontWeight: 'bold',
    color: '#6b7280',
    textTransform: 'uppercase',
  },
  fieldValueHeader: {
    flex: 1,
    fontSize: 9,
    fontWeight: 'bold',
    color: '#6b7280',
    textTransform: 'uppercase',
    textAlign: 'right',
  },
  docRow: {
    flexDirection: 'row',
    borderBottom: '1 solid #f3f4f6',
    paddingVertical: 4,
  },
  docName: {
    flex: 2,
    fontSize: 10,
    color: '#374151',
  },
  docExpiry: {
    flex: 1,
    fontSize: 9,
    color: '#6b7280',
    textAlign: 'right',
  },
  emptyText: {
    fontSize: 10,
    color: '#9ca3af',
    fontStyle: 'italic',
    paddingVertical: 4,
  },
  footerRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 20,
    paddingTop: 10,
    borderTop: '1 solid #e5e7eb',
  },
  footerText: {
    fontSize: 8,
    color: '#9ca3af',
  },
  qrContainer: {
    alignItems: 'center',
    marginTop: 10,
  },
  qrImage: {
    width: 60,
    height: 60,
  },
  qrLabel: {
    fontSize: 7,
    color: '#9ca3af',
    marginTop: 2,
  },
  locationText: {
    fontSize: 10,
    color: '#6b7280',
    marginBottom: 4,
  },
});

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/**
 * Format a field value for display in the PDF.
 * Returns "—" for null/undefined values per PDF-002.
 */
function formatFieldValue(value: unknown): string {
  if (value === null || value === undefined) return '—';
  if (typeof value === 'object') return JSON.stringify(value);
  return String(value);
}

/**
 * Format a date string for display.
 */
function formatDate(dateStr: string | null): string {
  if (!dateStr) return '—';
  const date = new Date(dateStr);
  if (isNaN(date.getTime())) return dateStr;
  return date.toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'short',
    day: 'numeric',
  });
}

// ---------------------------------------------------------------------------
// Document Component
// ---------------------------------------------------------------------------

export function ItemSheetDocument({
  itemName,
  itemSlug,
  status,
  itemType,
  fields,
  documents,
  projectName,
  qrDataUrl,
  locationPath,
  exportDate,
}: ItemSheetDocumentProps) {
  const hasDocuments = documents.length > 0;
  const hasQr = !!qrDataUrl;

  return (
    <Document>
      <Page size="A4" style={styles.page}>
        {/* Header */}
        <View style={styles.header}>
          <Text style={styles.headerTitle}>ManteMap — Item Sheet</Text>
          <Text style={styles.headerSubtitle}>Project: {projectName}</Text>
          <Text style={styles.headerDate}>Exported: {exportDate}</Text>
        </View>

        {/* Item Information */}
        <View style={styles.section}>
          <View style={styles.itemInfo}>
            <View style={{ flex: 3 }}>
              <Text style={styles.itemName}>{itemName}</Text>
              <Text style={styles.itemMeta}>Slug: {itemSlug}</Text>
              {itemType && (
                <Text style={styles.itemMeta}>Type: {itemType}</Text>
              )}
            </View>
            <View style={{ flex: 1, alignItems: 'flex-end' }}>
              {status && (
                <Text style={styles.badge}>{status}</Text>
              )}
            </View>
          </View>

          {locationPath && (
            <Text style={styles.locationText}>
              Location: {locationPath}
            </Text>
          )}
        </View>

        {/* Field Values (PDF-002) */}
        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Field Values</Text>
          {fields.length === 0 ? (
            <Text style={styles.emptyText}>No fields configured.</Text>
          ) : (
            <View style={styles.table}>
              <View style={styles.tableHeader}>
                <Text style={styles.fieldLabelHeader}>Field</Text>
                <Text style={styles.fieldValueHeader}>Value</Text>
              </View>
              {fields.map((field, index) => (
                <View style={styles.tableRow} key={index}>
                  <Text style={styles.fieldLabel}>{field.name}</Text>
                  <Text style={styles.fieldValue}>
                    {formatFieldValue(field.value)}
                  </Text>
                </View>
              ))}
            </View>
          )}
        </View>

        {/* Documents */}
        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Documents</Text>
          {!hasDocuments ? (
            <Text style={styles.emptyText}>No documents attached.</Text>
          ) : (
            <View style={styles.table}>
              <View style={styles.tableHeader}>
                <Text style={{ ...styles.fieldLabelHeader, flex: 2 }}>
                  Document
                </Text>
                <Text
                  style={{
                    ...styles.fieldValueHeader,
                    flex: 1,
                    textAlign: 'right',
                  }}
                >
                  Expires
                </Text>
              </View>
              {documents.map((doc, index) => (
                <View style={styles.docRow} key={index}>
                  <Text style={styles.docName}>{doc.name}</Text>
                  <Text style={styles.docExpiry}>
                    {formatDate(doc.expiresAt)}
                  </Text>
                </View>
              ))}
            </View>
          )}
        </View>

        {/* QR Code (PDF-003) — optional, gracefully omitted if unavailable */}
        {hasQr && (
          <View style={styles.qrContainer}>
            <Image src={qrDataUrl!} style={styles.qrImage} />
            <Text style={styles.qrLabel}>{itemSlug}</Text>
          </View>
        )}

        {/* Footer */}
        <View style={styles.footerRow}>
          <Text style={styles.footerText}>Generated by ManteMap</Text>
          <Text
            style={styles.footerText}
            render={({ pageNumber, totalPages }) =>
              `Page ${pageNumber} of ${totalPages}`
            }
          />
        </View>
      </Page>
    </Document>
  );
}
